### ISSUE TITLE
How About Signed Volume

### ISSUE THREAD

**Issue by NateTG** [thehans/FunctionalOpenSCAD#1]
I'm not sure what your stylistic sensibilities are, but there's a 'shoelace formula' for volume that seems like it would fight right in here:

```
function signed_volume(poly)=
   sum([ for(i=[0:len(poly[1])]
      _signed_volume(poly[0],poly[1][i])
   ])
;

function _signed_volume(points,face)=
   let( l=len(face) )
   (l>2)?
      sum([
         for(i=[1:l-2]) 
         cross(points[face[i]]-points[face[0]],points[face[i+1]]-points[face[i]])
   ])*points[face[0]]/6;
   :
      0
;
```

**Comment by thehans** [comment]
Do you have a link or reference for the algorithm used here?  I only find results for shoelace in relation to area.  

The code provided only returns `undef` for me, after fixing syntax error(missing close parenthesis).

**Comment by thehans** [comment]
Speaking of style, I'd do the first function something like this anyways:
```
function signed_volume(poly) =
  let(points = poly[0], faces = poly[1])
  sum([for(face = faces) _signed_volume(points, face) ]);
```

**Comment by NateTG** [comment]
Here's an algorithm reference. (Though that page gets a bit fancier.)
https://n-e-r-v-o-u-s.com/blog/?p=4415

I made it too complicated...

```
function _signed_volume(points,face)=
   let( l=len(face) )
   (l>2)?
      sum([ for(i=[1:l-2])
         cross(points[face[i]],points[face[i+1]])*points[face[0]]
      ])/6;
   :
      0
;
```
Both the 'shoelace algorithm' and this one are special cases of Stoke's Theorem.

**Comment by thehans** [comment]
Thanks @NateTG it appears work from the tests I've done.  I did swap the order of the cross() operation, because it seemed to expect the opposite winding order from OpenSCAD's convention(it was returning negative values for normal polyhedrons).  

I also rewrote the wrapper to support poly vectors.
