### ISSUE TITLE
Sum breaks the addition overload.

### ISSUE THREAD

**Issue by NateTG** [thehans/FunctionalOpenSCAD#2]
The way that sum is written here, it explicitly involves numbers, but in OpenSCAD, + works on other kinds of things.  Not explicitly involving 0 can save that for summation.

Consider this example:
```
function vsum(v,i=0) = len(v)-1 > i ? v[i] + vsum(v, i+1) : v[i];

echo(vsum([1,2,3]));

echo(vsum([[1,2,3],[4,5,6]]));

echo(sum([1,2,3]));

echo(sum([[1,2,3],[4,5,6]]));
```

**Comment by thehans** [comment]
The tradeoff then is that your version returns undef for an empty list, where I feel like the user might have expected 0.  I'm not sure if that's strictly better behavior.

```
echo(vsum([]));  // undefined
echo(sum([]));   // 0
```

Just as an aside: I don't recall exactly but I think I may have simply copied `sum` and a couple other of the small utility functions from a common library like MCAD or list-comprehension-demos.

**Comment by NateTG** [comment]
Fair enough.   0 and undefined are both reasonable ways to interpret an empty sum.

**Comment by thehans** [comment]
I was originally thinking that you meant to replace the sum function which I objected to.  But I suppose it doesn't hurt to add as an additional function if you see a need for it, so I've incuded it as vsum in functional.scad now
